name: Main CI

on:
  push:
    branches-ignore:
      # all commits merged from pull requests
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v3
      -
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          cache: true
      - run: dotnet restore -r linux-x64 --locked-mode
      - run: dotnet publish -r linux-x64